name: eshop-ui Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - run: npm run build-dev
    - name: Build the Docker image
      uses: actions/checkout@v4
    - run: docker build -t eshop-ui . --file Dockerfile
