name: eshop-ui Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build the eshop React App ${{matrix.node-version}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{matrix.node-version}}
        cache: 'npm'
    - run: npm ci
    - run: npm run build-dev

    
    - name: Build the Docker image and push to ACR
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push image to ACR
      run: az acr build --registry ${{ secrets.ACR_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --image "eshop-aks/ui":$(date +%Y%m%d%H%M%S) .